id: ID7D49747
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:05:36+00:00'
last_modified: '2022-06-10T09:21:43.083076+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ7445
  title: བཀའ་འགྱུར། ༼ལི་ཐང༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0A05:
      image_group_id: I1KG9868
      title: Volume 1 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 1
      base_file: 0A05.txt
    EEC1:
      image_group_id: I1KG9964
      title: Volume 97 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 97
      base_file: EEC1.txt
    56EE:
      image_group_id: I1KG9870
      title: Volume 3 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 3
      base_file: 56EE.txt
    '2585':
      image_group_id: I1KG9871
      title: Volume 4 of bka' 'gyur/ (li thang /)
      total_pages: 1228
      order: 4
      base_file: 2585.txt
    39CE:
      image_group_id: I1KG9872
      title: Volume 5 of bka' 'gyur/ (li thang /)
      total_pages: 603
      order: 5
      base_file: 39CE.txt
    7E96:
      image_group_id: I1KG9873
      title: Volume 6 of bka' 'gyur/ (li thang /)
      total_pages: 569
      order: 6
      base_file: 7E96.txt
    C483:
      image_group_id: I1KG9874
      title: Volume 7 of bka' 'gyur/ (li thang /)
      total_pages: 600
      order: 7
      base_file: C483.txt
    4CB9:
      image_group_id: I1KG9875
      title: Volume 8 of bka' 'gyur/ (li thang /)
      total_pages: 530
      order: 8
      base_file: 4CB9.txt
    22E5:
      image_group_id: I1KG9876
      title: Volume 9 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 9
      base_file: 22E5.txt
    94D4:
      image_group_id: I1KG9877
      title: Volume 10 of bka' 'gyur/ (li thang /)
      total_pages: 662
      order: 10
      base_file: 94D4.txt
    B35C:
      image_group_id: I1KG9878
      title: Volume 11 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 11
      base_file: B35C.txt
    EE61:
      image_group_id: I1KG9879
      title: Volume 12 of bka' 'gyur/ (li thang /)
      total_pages: 596
      order: 12
      base_file: EE61.txt
    '1862':
      image_group_id: I1KG9880
      title: Volume 13 of bka' 'gyur/ (li thang /)
      total_pages: 696
      order: 13
      base_file: 1862.txt
    6B38:
      image_group_id: I1KG9881
      title: Volume 14 of bka' 'gyur/ (li thang /)
      total_pages: 554
      order: 14
      base_file: 6B38.txt
    29B2:
      image_group_id: I1KG9882
      title: Volume 15 of bka' 'gyur/ (li thang /)
      total_pages: 552
      order: 15
      base_file: 29B2.txt
    CA11:
      image_group_id: I1KG9883
      title: Volume 16 of bka' 'gyur/ (li thang /)
      total_pages: 560
      order: 16
      base_file: CA11.txt
    '9544':
      image_group_id: I1KG9884
      title: Volume 17 of bka' 'gyur/ (li thang /)
      total_pages: 562
      order: 17
      base_file: 9544.txt
    69B2:
      image_group_id: I1KG9885
      title: Volume 18 of bka' 'gyur/ (li thang /)
      total_pages: 626
      order: 18
      base_file: 69B2.txt
    10C1:
      image_group_id: I1KG9886
      title: Volume 19 of bka' 'gyur/ (li thang /)
      total_pages: 598
      order: 19
      base_file: 10C1.txt
    05ED:
      image_group_id: I1KG9887
      title: Volume 20 of bka' 'gyur/ (li thang /)
      total_pages: 602
      order: 20
      base_file: 05ED.txt
    D67D:
      image_group_id: I1KG9888
      title: Volume 21 of bka' 'gyur/ (li thang /)
      total_pages: 586
      order: 21
      base_file: D67D.txt
    042F:
      image_group_id: I1KG9889
      title: Volume 22 of bka' 'gyur/ (li thang /)
      total_pages: 654
      order: 22
      base_file: 042F.txt
    65B8:
      image_group_id: I1KG9890
      title: Volume 23 of bka' 'gyur/ (li thang /)
      total_pages: 584
      order: 23
      base_file: 65B8.txt
    9B12:
      image_group_id: I1KG9891
      title: Volume 24 of bka' 'gyur/ (li thang /)
      total_pages: 615
      order: 24
      base_file: 9B12.txt
    62A7:
      image_group_id: I1KG9892
      title: Volume 25 of bka' 'gyur/ (li thang /)
      total_pages: 636
      order: 25
      base_file: 62A7.txt
    C121:
      image_group_id: I1KG9893
      title: Volume 26 of bka' 'gyur/ (li thang /)
      total_pages: 632
      order: 26
      base_file: C121.txt
    B8F1:
      image_group_id: I1KG9894
      title: Volume 27 of bka' 'gyur/ (li thang /)
      total_pages: 616
      order: 27
      base_file: B8F1.txt
    D404:
      image_group_id: I1KG9895
      title: Volume 28 of bka' 'gyur/ (li thang /)
      total_pages: 622
      order: 28
      base_file: D404.txt
    67B4:
      image_group_id: I1KG9896
      title: Volume 29 of bka' 'gyur/ (li thang /)
      total_pages: 624
      order: 29
      base_file: 67B4.txt
    3FE7:
      image_group_id: I1KG9897
      title: Volume 30 of bka' 'gyur/ (li thang /)
      total_pages: 630
      order: 30
      base_file: 3FE7.txt
    BA48:
      image_group_id: I1KG9898
      title: Volume 31 of bka' 'gyur/ (li thang /)
      total_pages: 642
      order: 31
      base_file: BA48.txt
    '6049':
      image_group_id: I1KG9899
      title: Volume 32 of bka' 'gyur/ (li thang /)
      total_pages: 608
      order: 32
      base_file: 6049.txt
    62E6:
      image_group_id: I1KG9900
      title: Volume 33 of bka' 'gyur/ (li thang /)
      total_pages: 618
      order: 33
      base_file: 62E6.txt
    DEBD:
      image_group_id: I1KG9901
      title: Volume 34 of bka' 'gyur/ (li thang /)
      total_pages: 572
      order: 34
      base_file: DEBD.txt
    AC81:
      image_group_id: I1KG9902
      title: Volume 35 of bka' 'gyur/ (li thang /)
      total_pages: 588
      order: 35
      base_file: AC81.txt
    06A8:
      image_group_id: I1KG9903
      title: Volume 36 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 36
      base_file: 06A8.txt
    B921:
      image_group_id: I1KG9904
      title: Volume 37 of bka' 'gyur/ (li thang /)
      total_pages: 593
      order: 37
      base_file: B921.txt
    7B13:
      image_group_id: I1KG9905
      title: Volume 38 of bka' 'gyur/ (li thang /)
      total_pages: 544
      order: 38
      base_file: 7B13.txt
    92F9:
      image_group_id: I1KG9906
      title: Volume 39 of bka' 'gyur/ (li thang /)
      total_pages: 617
      order: 39
      base_file: 92F9.txt
    CFE2:
      image_group_id: I1KG9907
      title: Volume 40 of bka' 'gyur/ (li thang /)
      total_pages: 718
      order: 40
      base_file: CFE2.txt
    '6278':
      image_group_id: I1KG9908
      title: Volume 41 of bka' 'gyur/ (li thang /)
      total_pages: 624
      order: 41
      base_file: 6278.txt
    A765:
      image_group_id: I1KG9909
      title: Volume 42 of bka' 'gyur/ (li thang /)
      total_pages: 651
      order: 42
      base_file: A765.txt
    948C:
      image_group_id: I1KG9910
      title: Volume 43 of bka' 'gyur/ (li thang /)
      total_pages: 608
      order: 43
      base_file: 948C.txt
    228C:
      image_group_id: I1KG9911
      title: Volume 44 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 44
      base_file: 228C.txt
    '8888':
      image_group_id: I1KG9912
      title: Volume 45 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 45
      base_file: 8888.txt
    00B3:
      image_group_id: I1KG9913
      title: Volume 46 of bka' 'gyur/ (li thang /)
      total_pages: 634
      order: 46
      base_file: 00B3.txt
    FE7B:
      image_group_id: I1KG9914
      title: Volume 47 of bka' 'gyur/ (li thang /)
      total_pages: 722
      order: 47
      base_file: FE7B.txt
    0FBB:
      image_group_id: I1KG9915
      title: Volume 48 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 48
      base_file: 0FBB.txt
    '4164':
      image_group_id: I1KG9916
      title: Volume 49 of bka' 'gyur/ (li thang /)
      total_pages: 568
      order: 49
      base_file: 4164.txt
    F7B2:
      image_group_id: I1KG9917
      title: Volume 50 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 50
      base_file: F7B2.txt
    '5453':
      image_group_id: I1KG9918
      title: Volume 51 of bka' 'gyur/ (li thang /)
      total_pages: 644
      order: 51
      base_file: 5453.txt
    0841:
      image_group_id: I1KG9919
      title: Volume 52 of bka' 'gyur/ (li thang /)
      total_pages: 586
      order: 52
      base_file: 0841.txt
    FE84:
      image_group_id: I1KG9920
      title: Volume 53 of bka' 'gyur/ (li thang /)
      total_pages: 722
      order: 53
      base_file: FE84.txt
    CC66:
      image_group_id: I1KG9921
      title: Volume 54 of bka' 'gyur/ (li thang /)
      total_pages: 628
      order: 54
      base_file: CC66.txt
    B357:
      image_group_id: I1KG9922
      title: Volume 55 of bka' 'gyur/ (li thang /)
      total_pages: 652
      order: 55
      base_file: B357.txt
    644E:
      image_group_id: I1KG9923
      title: Volume 56 of bka' 'gyur/ (li thang /)
      total_pages: 676
      order: 56
      base_file: 644E.txt
    8CEA:
      image_group_id: I1KG9924
      title: Volume 57 of bka' 'gyur/ (li thang /)
      total_pages: 680
      order: 57
      base_file: 8CEA.txt
    B443:
      image_group_id: I1KG9925
      title: Volume 58 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 58
      base_file: B443.txt
    '5993':
      image_group_id: I1KG9926
      title: Volume 59 of bka' 'gyur/ (li thang /)
      total_pages: 712
      order: 59
      base_file: 5993.txt
    '7866':
      image_group_id: I1KG9927
      title: Volume 60 of bka' 'gyur/ (li thang /)
      total_pages: 674
      order: 60
      base_file: 7866.txt
    54ED:
      image_group_id: I1KG9928
      title: Volume 61 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 61
      base_file: 54ED.txt
    A149:
      image_group_id: I1KG9929
      title: Volume 62 of bka' 'gyur/ (li thang /)
      total_pages: 688
      order: 62
      base_file: A149.txt
    CBF1:
      image_group_id: I1KG9930
      title: Volume 63 of bka' 'gyur/ (li thang /)
      total_pages: 666
      order: 63
      base_file: CBF1.txt
    AB14:
      image_group_id: I1KG9931
      title: Volume 64 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 64
      base_file: AB14.txt
    ACE3:
      image_group_id: I1KG9932
      title: Volume 65 of bka' 'gyur/ (li thang /)
      total_pages: 690
      order: 65
      base_file: ACE3.txt
    1AA1:
      image_group_id: I1KG9933
      title: Volume 66 of bka' 'gyur/ (li thang /)
      total_pages: 676
      order: 66
      base_file: 1AA1.txt
    2B24:
      image_group_id: I1KG9934
      title: Volume 67 of bka' 'gyur/ (li thang /)
      total_pages: 658
      order: 67
      base_file: 2B24.txt
    DAFF:
      image_group_id: I1KG9935
      title: Volume 68 of bka' 'gyur/ (li thang /)
      total_pages: 664
      order: 68
      base_file: DAFF.txt
    FB36:
      image_group_id: I1KG9936
      title: Volume 69 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 69
      base_file: FB36.txt
    5D77:
      image_group_id: I1KG9937
      title: Volume 70 of bka' 'gyur/ (li thang /)
      total_pages: 648
      order: 70
      base_file: 5D77.txt
    8A7D:
      image_group_id: I1KG9938
      title: Volume 71 of bka' 'gyur/ (li thang /)
      total_pages: 596
      order: 71
      base_file: 8A7D.txt
    FEBC:
      image_group_id: I1KG9939
      title: Volume 72 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 72
      base_file: FEBC.txt
    16A1:
      image_group_id: I1KG9940
      title: Volume 73 of bka' 'gyur/ (li thang /)
      total_pages: 475
      order: 73
      base_file: 16A1.txt
    17BF:
      image_group_id: I1KG9941
      title: Volume 74 of bka' 'gyur/ (li thang /)
      total_pages: 606
      order: 74
      base_file: 17BF.txt
    4D43:
      image_group_id: I1KG9942
      title: Volume 75 of bka' 'gyur/ (li thang /)
      total_pages: 516
      order: 75
      base_file: 4D43.txt
    CCCE:
      image_group_id: I1KG9943
      title: Volume 76 of bka' 'gyur/ (li thang /)
      total_pages: 594
      order: 76
      base_file: CCCE.txt
    '1609':
      image_group_id: I1KG9944
      title: Volume 77 of bka' 'gyur/ (li thang /)
      total_pages: 564
      order: 77
      base_file: 1609.txt
    A555:
      image_group_id: I1KG9945
      title: Volume 78 of bka' 'gyur/ (li thang /)
      total_pages: 634
      order: 78
      base_file: A555.txt
    C6C4:
      image_group_id: I1KG9946
      title: Volume 79 of bka' 'gyur/ (li thang /)
      total_pages: 682
      order: 79
      base_file: C6C4.txt
    909D:
      image_group_id: I1KG9947
      title: Volume 80 of bka' 'gyur/ (li thang /)
      total_pages: 716
      order: 80
      base_file: 909D.txt
    FFBC:
      image_group_id: I1KG9948
      title: Volume 81 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 81
      base_file: FFBC.txt
    04AE:
      image_group_id: I1KG9949
      title: Volume 82 of bka' 'gyur/ (li thang /)
      total_pages: 704
      order: 82
      base_file: 04AE.txt
    DA5E:
      image_group_id: I1KG9950
      title: Volume 83 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 83
      base_file: DA5E.txt
    DC9C:
      image_group_id: I1KG9951
      title: Volume 84 of bka' 'gyur/ (li thang /)
      total_pages: 670
      order: 84
      base_file: DC9C.txt
    1C4C:
      image_group_id: I1KG9952
      title: Volume 85 of bka' 'gyur/ (li thang /)
      total_pages: 710
      order: 85
      base_file: 1C4C.txt
    DD03:
      image_group_id: I1KG9953
      title: Volume 86 of bka' 'gyur/ (li thang /)
      total_pages: 774
      order: 86
      base_file: DD03.txt
    CBC6:
      image_group_id: I1KG9954
      title: Volume 87 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 87
      base_file: CBC6.txt
    9A70:
      image_group_id: I1KG9955
      title: Volume 88 of bka' 'gyur/ (li thang /)
      total_pages: 750
      order: 88
      base_file: 9A70.txt
    1C46:
      image_group_id: I1KG9956
      title: Volume 89 of bka' 'gyur/ (li thang /)
      total_pages: 654
      order: 89
      base_file: 1C46.txt
    '1017':
      image_group_id: I1KG9957
      title: Volume 90 of bka' 'gyur/ (li thang /)
      total_pages: 506
      order: 90
      base_file: 1017.txt
    476B:
      image_group_id: I1KG9958
      title: Volume 91 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 91
      base_file: 476B.txt
    AAAC:
      image_group_id: I1KG9959
      title: Volume 92 of bka' 'gyur/ (li thang /)
      total_pages: 670
      order: 92
      base_file: AAAC.txt
    '7555':
      image_group_id: I1KG9960
      title: Volume 93 of bka' 'gyur/ (li thang /)
      total_pages: 621
      order: 93
      base_file: 7555.txt
    AD44:
      image_group_id: I1KG9961
      title: Volume 94 of bka' 'gyur/ (li thang /)
      total_pages: 614
      order: 94
      base_file: AD44.txt
    92BB:
      image_group_id: I1KG9962
      title: Volume 95 of bka' 'gyur/ (li thang /)
      total_pages: 612
      order: 95
      base_file: 92BB.txt
    11C9:
      image_group_id: I1KG9963
      title: Volume 96 of bka' 'gyur/ (li thang /)
      total_pages: 602
      order: 96
      base_file: 11C9.txt
    4E55:
      image_group_id: I1KG9965
      title: Volume 98 of bka' 'gyur/ (li thang /)
      total_pages: 640
      order: 98
      base_file: 4E55.txt
    28CD:
      image_group_id: I1KG9966
      title: Volume 99 of bka' 'gyur/ (li thang /)
      total_pages: 656
      order: 99
      base_file: 28CD.txt
    E40E:
      image_group_id: I1KG9967
      title: Volume 100 of bka' 'gyur/ (li thang /)
      total_pages: 3
      order: 100
      base_file: E40E.txt
    DD88:
      image_group_id: I1KG9968
      title: Volume 101 of bka' 'gyur/ (li thang /)
      total_pages: 690
      order: 101
      base_file: DD88.txt
    1DC3:
      image_group_id: I1KG9969
      title: Volume 102 of bka' 'gyur/ (li thang /)
      total_pages: 696
      order: 102
      base_file: 1DC3.txt
    3F90:
      image_group_id: I1KG9970
      title: Volume 103 of bka' 'gyur/ (li thang /)
      total_pages: 616
      order: 103
      base_file: 3F90.txt
    0288:
      image_group_id: I1KG9971
      title: Volume 104 of bka' 'gyur/ (li thang /)
      total_pages: 534
      order: 104
      base_file: 0288.txt
    FF2F:
      image_group_id: I1KG9972
      title: Volume 105 of bka' 'gyur/ (li thang /)
      total_pages: 610
      order: 105
      base_file: FF2F.txt
    FBAB:
      image_group_id: I1KG9973
      title: Volume 106 of bka' 'gyur/ (li thang /)
      total_pages: 554
      order: 106
      base_file: FBAB.txt
    A872:
      image_group_id: I1KG9974
      title: Volume 107 of bka' 'gyur/ (li thang /)
      total_pages: 505
      order: 107
      base_file: A872.txt
    44FC:
      image_group_id: I1KG9975
      title: Volume 108 of bka' 'gyur/ (li thang /)
      total_pages: 449
      order: 108
      base_file: 44FC.txt
    F33F:
      image_group_id: I1KG9976
      title: Volume 109 of bka' 'gyur/ (li thang /)
      total_pages: 139
      order: 109
      base_file: F33F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
